name: ourfloworks
services:
- name: ourfloworks
  source_dir: .
  github:
    repo: machine-squelch/ourfloworks
    branch: main
    deploy_on_push: true
  build_command: npm install
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-s
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: PORT
    scope: RUN_TIME
    value: "8080"
  - key: NPM_CONFIG_PRODUCTION
    scope: RUN_AND_BUILD_TIME
    value: "true"
  - key: USE_NPM_INSTALL
    scope: RUN_AND_BUILD_TIME
    value: "true"
  # health_check:
  #   http_path: /health
  #   initial_delay_seconds: 60
  #   period_seconds: 10
  #   timeout_seconds: 5
  #   success_threshold: 1
  #   failure_threshold: 3

